// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TrackingCodeApi.models;

#nullable disable

namespace TrackingCodeApi.Migrations
{
    [DbContext(typeof(TrackingCodeDb))]
    [Migration("20251029021832_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("RM558785")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrackingCodeApi.models.Auditoria", b =>
                {
                    b.Property<int>("IdAudit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_audit");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAudit"));

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_operacao");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_funcionario");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("tipo_operacao");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("valores_anteriores");

                    b.Property<string>("ValoresNovos")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("valores_novos");

                    b.HasKey("IdAudit");

                    b.HasIndex("IdFuncionario");

                    b.ToTable("AUDITORIA_MOVIMENTACAO", "RM558785");
                });

            modelBuilder.Entity("TrackingCodeApi.models.Localizacao", b =>
                {
                    b.Property<int>("IdLocalizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_localizacao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocalizacao"));

                    b.Property<int>("CodigoTag")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("codigo_tag");

                    b.Property<int>("IdSetor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_setor");

                    b.Property<decimal>("X")
                        .HasPrecision(18, 6)
                        .HasColumnType("DECIMAL(18,6)")
                        .HasColumnName("x");

                    b.Property<decimal>("Y")
                        .HasPrecision(18, 6)
                        .HasColumnType("DECIMAL(18,6)")
                        .HasColumnName("y");

                    b.HasKey("IdLocalizacao");

                    b.HasIndex("CodigoTag");

                    b.HasIndex("IdSetor");

                    b.ToTable("localizacao", "RM558785");
                });

            modelBuilder.Entity("TrackingCodeApi.models.Moto", b =>
                {
                    b.Property<string>("Chassi")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("chassi");

                    b.Property<int?>("AuditoriaIdAudit")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CodigoTag")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("codigo_tag");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_cadastro");

                    b.Property<int?>("IdAudit")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_audit");

                    b.Property<int>("IdSetor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_setor");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("placa");

                    b.Property<int>("SetorIdSetor")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Chassi");

                    b.HasIndex("AuditoriaIdAudit");

                    b.HasIndex("CodigoTag")
                        .IsUnique();

                    b.HasIndex("SetorIdSetor");

                    b.ToTable("MOTO", "RM558785");
                });

            modelBuilder.Entity("TrackingCodeApi.models.Setor", b =>
                {
                    b.Property<int>("IdSetor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_setor");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSetor"));

                    b.Property<double?>("CoordenadasLimite")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("coordenadas_limite");

                    b.Property<string>("Descricao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nome");

                    b.HasKey("IdSetor");

                    b.ToTable("setor", "RM558785");
                });

            modelBuilder.Entity("TrackingCodeApi.models.Tag", b =>
                {
                    b.Property<int>("CodigoTag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("codigo_tag");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoTag"));

                    b.Property<string>("Chassi")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("chassi");

                    b.Property<DateTime>("DataVinculo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_vinculo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("status");

                    b.HasKey("CodigoTag");

                    b.ToTable("tag", "RM558785");
                });

            modelBuilder.Entity("TrackingCodeApi.models.Usuario", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuncionario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdFuncionario");

                    b.ToTable("USUARIO", "RM558785");
                });

            modelBuilder.Entity("TrackingCodeApi.models.Auditoria", b =>
                {
                    b.HasOne("TrackingCodeApi.models.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TrackingCodeApi.models.Localizacao", b =>
                {
                    b.HasOne("TrackingCodeApi.models.Tag", "Tag")
                        .WithMany("Localizacoes")
                        .HasForeignKey("CodigoTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackingCodeApi.models.Setor", "Setor")
                        .WithMany("Localizacoes")
                        .HasForeignKey("IdSetor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TrackingCodeApi.models.Moto", b =>
                {
                    b.HasOne("TrackingCodeApi.models.Auditoria", "Auditoria")
                        .WithMany()
                        .HasForeignKey("AuditoriaIdAudit");

                    b.HasOne("TrackingCodeApi.models.Tag", "Tag")
                        .WithOne("Moto")
                        .HasForeignKey("TrackingCodeApi.models.Moto", "CodigoTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackingCodeApi.models.Setor", "Setor")
                        .WithMany("Motos")
                        .HasForeignKey("SetorIdSetor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auditoria");

                    b.Navigation("Setor");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TrackingCodeApi.models.Setor", b =>
                {
                    b.Navigation("Localizacoes");

                    b.Navigation("Motos");
                });

            modelBuilder.Entity("TrackingCodeApi.models.Tag", b =>
                {
                    b.Navigation("Localizacoes");

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("TrackingCodeApi.models.Usuario", b =>
                {
                    b.Navigation("Auditorias");
                });
#pragma warning restore 612, 618
        }
    }
}
